services:
  echo_api_1:
    build: .
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - go-redis-echo-test
    depends_on:
      - dragonfly
  echo_api_2:
    build: .
    environment:
      - PORT=3001
    ports:
      - "3001:3000"
    networks:
      - go-redis-echo-test
    depends_on:
      - dragonfly
  echo_api_3:
    build: .
    environment:
      - PORT=3002
    ports:
      - "3002:3000"
    networks:
      - go-redis-echo-test
    depends_on:
      - dragonfly
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - go-redis-echo-test
    depends_on:
      - echo_api_1
      - echo_api_2
      - echo_api_3
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    command: --cluster_mode=emulated --lock_on_hashtags
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./data/df:/data
    networks:
      - go-redis-echo-test
networks:
  go-redis-echo-test:
    driver: bridge
